### ISSUE TITLE
Feature: Compact mode

### ISSUE THREAD

**Issue by underyx** [Strajk/refined-trello#6]
I like this look even more:
![](https://i.imgur.com/72aBNZj.png)

Achieved with

``` css
.list-card {
  margin-bottom: 0;
  border-radius: 0;
}
```

A Cozy/Compact setting might be nice to adjust this?
